In [32]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
import itertools

In [38]:
df=pd.read_csv("sample_dataset_v3.csv")
df1=df.head()
df1

,Billing Date,Brand,Article,Site,Site Area,MRP,Promotion Name,Region,POS Billing Quantity,POS Cost,...,Wash Care Instructions,C Technique,Broad Craft,Handloom Mark,Silk Mark,Type,Style Code,Craft Code,Site Name,Bin
0,2023-03-09,Biba,6517116692,ST40,A,7282,P37,R4,1,3486.742249,...,Handwash Separately,C6,B1,no,no,Printed,6517116,C6,ST40A,7000-7999
1,2023-01-10,Ciba,9792126013,ST35,B,6891,P20,R2,1,3366.377476,...,Handwash Separately,C3,B1,no,no,Embroidered,9792126,C3,ST35B,6000-6999
2,2023-01-30,Aiba,2451609893,ST13,A,1373,P16,R1,1,621.996417,...,Handwash Separately,C8,B1,no,no,Tie-Dyed,2451609,C8,ST13A,1000-1999
3,2023-02-08,Ciba,6919239963,ST24,A,4452,P2,R4,1,2182.635892,...,Handwash Separately,C6,B2,no,no,Embroidered,6919239,C6,ST24A,4000-4999
4,2023-01-01,Ciba,1418488906,ST25,B,5220,P13,R1,1,2421.383859,...,Handwash Separately,C4,B2,no,no,Embroidered,1418488,C4,ST25B,5000-5999

In [39]:
df1.columns

Index(['Billing Date', 'Brand', 'Article', 'Site', 'Site Area', 'MRP',
       'Promotion Name', 'Region', 'POS Billing Quantity', 'POS Cost',
       'POS Gross Sales', 'POS Total Discount', 'POS Tax Amount',
       'POS Net Sales WOT', 'POS RGM', 'Vendor', 'Fiber', 'Fabric',
       'Brand Tag', 'Wash Care Instructions', 'C Technique', 'Broad Craft',
       'Handloom Mark', 'Silk Mark', 'Type', 'Style Code', 'Craft Code',
       'Site Name', 'Bin'],
      dtype='object')

The dataset contains 5 dates which are not in order. I would like to complete the dataset by filling in all the intervening dates brand and sites. I would put a zero with all such columns filled. I would have to take care that I do not introduce any row where for a particular date, brand and site there is already a row

In [40]:
df1['Billing Date']=pd.to_datetime(df1['Billing Date'])

C:\Users\asus\AppData\Local\Temp\ipykernel_7864\376283826.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Billing Date']=pd.to_datetime(df1['Billing Date'])

### Get the start_date and the end_date

In [41]:
# Calculate the start date and end date
start_date=df1['Billing Date'].min().replace(day=1)
end_date=df1['Billing Date'].max()
start_date,end_date

(Timestamp('2023-01-01 00:00:00'), Timestamp('2023-03-09 00:00:00'))

### Change the start_date to 1st of that month
In this case it starts from 1st of the month. But suppose I want to start the date from 1st of the month, in case this date is not first, say 2023-01-08

In [42]:
start_date = start_date.replace(day=1)
start_date

Timestamp('2023-01-01 00:00:00')

### Calculating the Date Range

In [43]:
date_range=pd.date_range(start=start_date,end=end_date)
date_range

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
               '2023-01-09', '2023-01-10', '2023-01-11', '2023-01-12',
               '2023-01-13', '2023-01-14', '2023-01-15', '2023-01-16',
               '2023-01-17', '2023-01-18', '2023-01-19', '2023-01-20',
               '2023-01-21', '2023-01-22', '2023-01-23', '2023-01-24',
               '2023-01-25', '2023-01-26', '2023-01-27', '2023-01-28',
               '2023-01-29', '2023-01-30', '2023-01-31', '2023-02-01',
               '2023-02-02', '2023-02-03', '2023-02-04', '2023-02-05',
               '2023-02-06', '2023-02-07', '2023-02-08', '2023-02-09',
               '2023-02-10', '2023-02-11', '2023-02-12', '2023-02-13',
               '2023-02-14', '2023-02-15', '2023-02-16', '2023-02-17',
               '2023-02-18', '2023-02-19', '2023-02-20', '2023-02-21',
               '2023-02-22', '2023-02-23', '2023-02-24', '2023-02-25',
               '2023-02-26', '2023-02-27', '2023-02-28', '2023-03-01',
               '2023-03-02', '2023-03-03', '2023-03-04', '2023-03-05',
               '2023-03-06', '2023-03-07', '2023-03-08', '2023-03-09'],
              dtype='datetime64[ns]', freq='D')

### Get Unique Brands

In [44]:
unique_brands=df1['Brand'].unique()
unique_brands

array(['Biba', 'Ciba', 'Aiba'], dtype=object)

### Get Unique Site Names

In [45]:
unique_site=df1['Site Name'].unique()
unique_site

array(['ST40A', 'ST35B', 'ST13A', 'ST24A', 'ST25B'], dtype=object)

### Generate unique combinations of date_range, unique_brands and unique_site

In [46]:
combinations= list(itertools.product(date_range,unique_brands, unique_site))
combinations

[(Timestamp('2023-01-01 00:00:00', freq='D'), 'Biba', 'ST40A'),
 (Timestamp('2023-01-01 00:00:00', freq='D'), 'Biba', 'ST35B'),
 (Timestamp('2023-01-01 00:00:00', freq='D'), 'Biba', 'ST13A'),
 (Timestamp('2023-01-01 00:00:00', freq='D'), 'Biba', 'ST24A'),
 (Timestamp('2023-01-01 00:00:00', freq='D'), 'Biba', 'ST25B'),
 (Timestamp('2023-01-01 00:00:00', freq='D'), 'Ciba', 'ST40A'),
 (Timestamp('2023-01-01 00:00:00', freq='D'), 'Ciba', 'ST35B'),
 (Timestamp('2023-01-01 00:00:00', freq='D'), 'Ciba', 'ST13A'),
 (Timestamp('2023-01-01 00:00:00', freq='D'), 'Ciba', 'ST24A'),
 (Timestamp('2023-01-01 00:00:00', freq='D'), 'Ciba', 'ST25B'),
 (Timestamp('2023-01-01 00:00:00', freq='D'), 'Aiba', 'ST40A'),
 (Timestamp('2023-01-01 00:00:00', freq='D'), 'Aiba', 'ST35B'),
 (Timestamp('2023-01-01 00:00:00', freq='D'), 'Aiba', 'ST13A'),
 (Timestamp('2023-01-01 00:00:00', freq='D'), 'Aiba', 'ST24A'),
 (Timestamp('2023-01-01 00:00:00', freq='D'), 'Aiba', 'ST25B'),
 (Timestamp('2023-01-02 00:00:00', freq='D'), 'Biba', 'ST40A'),
 (Timestamp('2023-01-02 00:00:00', freq='D'), 'Biba', 'ST35B'),
 (Timestamp('2023-01-02 00:00:00', freq='D'), 'Biba', 'ST13A'),
 (Timestamp('2023-01-02 00:00:00', freq='D'), 'Biba', 'ST24A'),
 (Timestamp('2023-01-02 00:00:00', freq='D'), 'Biba', 'ST25B'),
 (Timestamp('2023-01-02 00:00:00', freq='D'), 'Ciba', 'ST40A'),
 (Timestamp('2023-01-02 00:00:00', freq='D'), 'Ciba', 'ST35B'),
 (Timestamp('2023-01-02 00:00:00', freq='D'), 'Ciba', 'ST13A'),
 (Timestamp('2023-01-02 00:00:00', freq='D'), 'Ciba', 'ST24A'),
 (Timestamp('2023-01-02 00:00:00', freq='D'), 'Ciba', 'ST25B'),
 (Timestamp('2023-01-02 00:00:00', freq='D'), 'Aiba', 'ST40A'),
 (Timestamp('2023-01-02 00:00:00', freq='D'), 'Aiba', 'ST35B'),
 (Timestamp('2023-01-02 00:00:00', freq='D'), 'Aiba', 'ST13A'),
 (Timestamp('2023-01-02 00:00:00', freq='D'), 'Aiba', 'ST24A'),
 (Timestamp('2023-01-02 00:00:00', freq='D'), 'Aiba', 'ST25B'),
 (Timestamp('2023-01-03 00:00:00', freq='D'), 'Biba', 'ST40A'),
 (Timestamp('2023-01-03 00:00:00', freq='D'), 'Biba', 'ST35B'),
 (Timestamp('2023-01-03 00:00:00', freq='D'), 'Biba', 'ST13A'),
 (Timestamp('2023-01-03 00:00:00', freq='D'), 'Biba', 'ST24A'),
 (Timestamp('2023-01-03 00:00:00', freq='D'), 'Biba', 'ST25B'),
 (Timestamp('2023-01-03 00:00:00', freq='D'), 'Ciba', 'ST40A'),
 (Timestamp('2023-01-03 00:00:00', freq='D'), 'Ciba', 'ST35B'),
 (Timestamp('2023-01-03 00:00:00', freq='D'), 'Ciba', 'ST13A'),
 (Timestamp('2023-01-03 00:00:00', freq='D'), 'Ciba', 'ST24A'),
 (Timestamp('2023-01-03 00:00:00', freq='D'), 'Ciba', 'ST25B'),
 (Timestamp('2023-01-03 00:00:00', freq='D'), 'Aiba', 'ST40A'),
 (Timestamp('2023-01-03 00:00:00', freq='D'), 'Aiba', 'ST35B'),
 (Timestamp('2023-01-03 00:00:00', freq='D'), 'Aiba', 'ST13A'),
 (Timestamp('2023-01-03 00:00:00', freq='D'), 'Aiba', 'ST24A'),
 (Timestamp('2023-01-03 00:00:00', freq='D'), 'Aiba', 'ST25B'),
 (Timestamp('2023-01-04 00:00:00', freq='D'), 'Biba', 'ST40A'),
 (Timestamp('2023-01-04 00:00:00', freq='D'), 'Biba', 'ST35B'),
 (Timestamp('2023-01-04 00:00:00', freq='D'), 'Biba', 'ST13A'),
 (Timestamp('2023-01-04 00:00:00', freq='D'), 'Biba', 'ST24A'),
 (Timestamp('2023-01-04 00:00:00', freq='D'), 'Biba', 'ST25B'),
 (Timestamp('2023-01-04 00:00:00', freq='D'), 'Ciba', 'ST40A'),
 (Timestamp('2023-01-04 00:00:00', freq='D'), 'Ciba', 'ST35B'),
 (Timestamp('2023-01-04 00:00:00', freq='D'), 'Ciba', 'ST13A'),
 (Timestamp('2023-01-04 00:00:00', freq='D'), 'Ciba', 'ST24A'),
 (Timestamp('2023-01-04 00:00:00', freq='D'), 'Ciba', 'ST25B'),
 (Timestamp('2023-01-04 00:00:00', freq='D'), 'Aiba', 'ST40A'),
 (Timestamp('2023-01-04 00:00:00', freq='D'), 'Aiba', 'ST35B'),
 (Timestamp('2023-01-04 00:00:00', freq='D'), 'Aiba', 'ST13A'),
 (Timestamp('2023-01-04 00:00:00', freq='D'), 'Aiba', 'ST24A'),
 (Timestamp('2023-01-04 00:00:00', freq='D'), 'Aiba', 'ST25B'),
 (Timestamp('2023-01-05 00:00:00', freq='D'), 'Biba', 'ST40A'),
 (Timestamp('2023-01-05 00:00:00', freq='D'), 'Biba', 'ST35B'),
 (Timestamp('2023-01-05 00:00:00', freq='D'), 'Biba', 'ST13A'),
 (Timestamp('2023-01-05 00:00:00', freq='D'), 'Biba', 'ST24A'),
 (Timestamp('2023-01-05 00:00:00', freq='D'), 'Biba', 'ST25B'),
 (Timestamp('2023-01-05 00:00:00', freq='D'), 'Ciba', 'ST40A'),
 (Timestamp('2023-01-05 00:00:00', freq='D'), 'Ciba', 'ST35B'),
 (Timestamp('2023-01-05 00:00:00', freq='D'), 'Ciba', 'ST13A'),
 (Timestamp('2023-01-05 00:00:00', freq='D'), 'Ciba', 'ST24A'),
 (Timestamp('2023-01-05 00:00:00', freq='D'), 'Ciba', 'ST25B'),
 (Timestamp('2023-01-05 00:00:00', freq='D'), 'Aiba', 'ST40A'),
 (Timestamp('2023-01-05 00:00:00', freq='D'), 'Aiba', 'ST35B'),
 (Timestamp('2023-01-05 00:00:00', freq='D'), 'Aiba', 'ST13A'),
 (Timestamp('2023-01-05 00:00:00', freq='D'), 'Aiba', 'ST24A'),
 (Timestamp('2023-01-05 00:00:00', freq='D'), 'Aiba', 'ST25B'),
 (Timestamp('2023-01-06 00:00:00', freq='D'), 'Biba', 'ST40A'),
 (Timestamp('2023-01-06 00:00:00', freq='D'), 'Biba', 'ST35B'),
 (Timestamp('2023-01-06 00:00:00', freq='D'), 'Biba', 'ST13A'),
 (Timestamp('2023-01-06 00:00:00', freq='D'), 'Biba', 'ST24A'),
 (Timestamp('2023-01-06 00:00:00', freq='D'), 'Biba', 'ST25B'),
 (Timestamp('2023-01-06 00:00:00', freq='D'), 'Ciba', 'ST40A'),
 (Timestamp('2023-01-06 00:00:00', freq='D'), 'Ciba', 'ST35B'),
 (Timestamp('2023-01-06 00:00:00', freq='D'), 'Ciba', 'ST13A'),
 (Timestamp('2023-01-06 00:00:00', freq='D'), 'Ciba', 'ST24A'),
 (Timestamp('2023-01-06 00:00:00', freq='D'), 'Ciba', 'ST25B'),
 (Timestamp('2023-01-06 00:00:00', freq='D'), 'Aiba', 'ST40A'),
 (Timestamp('2023-01-06 00:00:00', freq='D'), 'Aiba', 'ST35B'),
 (Timestamp('2023-01-06 00:00:00', freq='D'), 'Aiba', 'ST13A'),
 (Timestamp('2023-01-06 00:00:00', freq='D'), 'Aiba', 'ST24A'),
 (Timestamp('2023-01-06 00:00:00', freq='D'), 'Aiba', 'ST25B'),
 (Timestamp('2023-01-07 00:00:00', freq='D'), 'Biba', 'ST40A'),
 (Timestamp('2023-01-07 00:00:00', freq='D'), 'Biba', 'ST35B'),
 (Timestamp('2023-01-07 00:00:00', freq='D'), 'Biba', 'ST13A'),
 (Timestamp('2023-01-07 00:00:00', freq='D'), 'Biba', 'ST24A'),
 (Timestamp('2023-01-07 00:00:00', freq='D'), 'Biba', 'ST25B'),
 (Timestamp('2023-01-07 00:00:00', freq='D'), 'Ciba', 'ST40A'),
 (Timestamp('2023-01-07 00:00:00', freq='D'), 'Ciba', 'ST35B'),
 (Timestamp('2023-01-07 00:00:00', freq='D'), 'Ciba', 'ST13A'),
 (Timestamp('2023-01-07 00:00:00', freq='D'), 'Ciba', 'ST24A'),
 (Timestamp('2023-01-07 00:00:00', freq='D'), 'Ciba', 'ST25B'),
 (Timestamp('2023-01-07 00:00:00', freq='D'), 'Aiba', 'ST40A'),
 (Timestamp('2023-01-07 00:00:00', freq='D'), 'Aiba', 'ST35B'),
 (Timestamp('2023-01-07 00:00:00', freq='D'), 'Aiba', 'ST13A'),
 (Timestamp('2023-01-07 00:00:00', freq='D'), 'Aiba', 'ST24A'),
 (Timestamp('2023-01-07 00:00:00', freq='D'), 'Aiba', 'ST25B'),
 (Timestamp('2023-01-08 00:00:00', freq='D'), 'Biba', 'ST40A'),
 (Timestamp('2023-01-08 00:00:00', freq='D'), 'Biba', 'ST35B'),
 (Timestamp('2023-01-08 00:00:00', freq='D'), 'Biba', 'ST13A'),
 (Timestamp('2023-01-08 00:00:00', freq='D'), 'Biba', 'ST24A'),
 (Timestamp('2023-01-08 00:00:00', freq='D'), 'Biba', 'ST25B'),
 (Timestamp('2023-01-08 00:00:00', freq='D'), 'Ciba', 'ST40A'),
 (Timestamp('2023-01-08 00:00:00', freq='D'), 'Ciba', 'ST35B'),
 (Timestamp('2023-01-08 00:00:00', freq='D'), 'Ciba', 'ST13A'),
 (Timestamp('2023-01-08 00:00:00', freq='D'), 'Ciba', 'ST24A'),
 (Timestamp('2023-01-08 00:00:00', freq='D'), 'Ciba', 'ST25B'),
 (Timestamp('2023-01-08 00:00:00', freq='D'), 'Aiba', 'ST40A'),
 (Timestamp('2023-01-08 00:00:00', freq='D'), 'Aiba', 'ST35B'),
 (Timestamp('2023-01-08 00:00:00', freq='D'), 'Aiba', 'ST13A'),
 (Timestamp('2023-01-08 00:00:00', freq='D'), 'Aiba', 'ST24A'),
 (Timestamp('2023-01-08 00:00:00', freq='D'), 'Aiba', 'ST25B'),
 (Timestamp('2023-01-09 00:00:00', freq='D'), 'Biba', 'ST40A'),
 (Timestamp('2023-01-09 00:00:00', freq='D'), 'Biba', 'ST35B'),
 (Timestamp('2023-01-09 00:00:00', freq='D'), 'Biba', 'ST13A'),
 (Timestamp('2023-01-09 00:00:00', freq='D'), 'Biba', 'ST24A'),
 (Timestamp('2023-01-09 00:00:00', freq='D'), 'Biba', 'ST25B'),
 (Timestamp('2023-01-09 00:00:00', freq='D'), 'Ciba', 'ST40A'),
 (Timestamp('2023-01-09 00:00:00', freq='D'), 'Ciba', 'ST35B'),
 (Timestamp('2023-01-09 00:00:00', freq='D'), 'Ciba', 'ST13A'),
 (Timestamp('2023-01-09 00:00:00', freq='D'), 'Ciba', 'ST24A'),
 (Timestamp('2023-01-09 00:00:00', freq='D'), 'Ciba', 'ST25B'),
 (Timestamp('2023-01-09 00:00:00', freq='D'), 'Aiba', 'ST40A'),
 (Timestamp('2023-01-09 00:00:00', freq='D'), 'Aiba', 'ST35B'),
 (Timestamp('2023-01-09 00:00:00', freq='D'), 'Aiba', 'ST13A'),
 (Timestamp('2023-01-09 00:00:00', freq='D'), 'Aiba', 'ST24A'),
 (Timestamp('2023-01-09 00:00:00', freq='D'), 'Aiba', 'ST25B'),
 (Timestamp('2023-01-10 00:00:00', freq='D'), 'Biba', 'ST40A'),
 (Timestamp('2023-01-10 00:00:00', freq='D'), 'Biba', 'ST35B'),
 (Timestamp('2023-01-10 00:00:00', freq='D'), 'Biba', 'ST13A'),
 (Timestamp('2023-01-10 00:00:00', freq='D'), 'Biba', 'ST24A'),
 (Timestamp('2023-01-10 00:00:00', freq='D'), 'Biba', 'ST25B'),
 (Timestamp('2023-01-10 00:00:00', freq='D'), 'Ciba', 'ST40A'),
 (Timestamp('2023-01-10 00:00:00', freq='D'), 'Ciba', 'ST35B'),
 (Timestamp('2023-01-10 00:00:00', freq='D'), 'Ciba', 'ST13A'),
 (Timestamp('2023-01-10 00:00:00', freq='D'), 'Ciba', 'ST24A'),
 (Timestamp('2023-01-10 00:00:00', freq='D'), 'Ciba', 'ST25B'),
 (Timestamp('2023-01-10 00:00:00', freq='D'), 'Aiba', 'ST40A'),
 (Timestamp('2023-01-10 00:00:00', freq='D'), 'Aiba', 'ST35B'),
 (Timestamp('2023-01-10 00:00:00', freq='D'), 'Aiba', 'ST13A'),
 (Timestamp('2023-01-10 00:00:00', freq='D'), 'Aiba', 'ST24A'),
 (Timestamp('2023-01-10 00:00:00', freq='D'), 'Aiba', 'ST25B'),
 (Timestamp('2023-01-11 00:00:00', freq='D'), 'Biba', 'ST40A'),
 (Timestamp('2023-01-11 00:00:00', freq='D'), 'Biba', 'ST35B'),
 (Timestamp('2023-01-11 00:00:00', freq='D'), 'Biba', 'ST13A'),
 (Timestamp('2023-01-11 00:00:00', freq='D'), 'Biba', 'ST24A'),
 (Timestamp('2023-01-11 00:00:00', freq='D'), 'Biba', 'ST25B'),
 (Timestamp('2023-01-11 00:00:00', freq='D'), 'Ciba', 'ST40A'),
 (Timestamp('2023-01-11 00:00:00', freq='D'), 'Ciba', 'ST35B'),
 (Timestamp('2023-01-11 00:00:00', freq='D'), 'Ciba', 'ST13A'),
 (Timestamp('2023-01-11 00:00:00', freq='D'), 'Ciba', 'ST24A'),
 (Timestamp('2023-01-11 00:00:00', freq='D'), 'Ciba', 'ST25B'),
 (Timestamp('2023-01-11 00:00:00', freq='D'), 'Aiba', 'ST40A'),
 (Timestamp('2023-01-11 00:00:00', freq='D'), 'Aiba', 'ST35B'),
 (Timestamp('2023-01-11 00:00:00', freq='D'), 'Aiba', 'ST13A'),
 (Timestamp('2023-01-11 00:00:00', freq='D'), 'Aiba', 'ST24A'),
 (Timestamp('2023-01-11 00:00:00', freq='D'), 'Aiba', 'ST25B'),
 (Timestamp('2023-01-12 00:00:00', freq='D'), 'Biba', 'ST40A'),
 (Timestamp('2023-01-12 00:00:00', freq='D'), 'Biba', 'ST35B'),
 (Timestamp('2023-01-12 00:00:00', freq='D'), 'Biba', 'ST13A'),
 (Timestamp('2023-01-12 00:00:00', freq='D'), 'Biba', 'ST24A'),
 (Timestamp('2023-01-12 00:00:00', freq='D'), 'Biba', 'ST25B'),
 (Timestamp('2023-01-12 00:00:00', freq='D'), 'Ciba', 'ST40A'),
 (Timestamp('2023-01-12 00:00:00', freq='D'), 'Ciba', 'ST35B'),
 (Timestamp('2023-01-12 00:00:00', freq='D'), 'Ciba', 'ST13A'),
 (Timestamp('2023-01-12 00:00:00', freq='D'), 'Ciba', 'ST24A'),
 (Timestamp('2023-01-12 00:00:00', freq='D'), 'Ciba', 'ST25B'),
 (Timestamp('2023-01-12 00:00:00', freq='D'), 'Aiba', 'ST40A'),
 (Timestamp('2023-01-12 00:00:00', freq='D'), 'Aiba', 'ST35B'),
 (Timestamp('2023-01-12 00:00:00', freq='D'), 'Aiba', 'ST13A'),
 (Timestamp('2023-01-12 00:00:00', freq='D'), 'Aiba', 'ST24A'),
 (Timestamp('2023-01-12 00:00:00', freq='D'), 'Aiba', 'ST25B'),
 (Timestamp('2023-01-13 00:00:00', freq='D'), 'Biba', 'ST40A'),
 (Timestamp('2023-01-13 00:00:00', freq='D'), 'Biba', 'ST35B'),
 (Timestamp('2023-01-13 00:00:00', freq='D'), 'Biba', 'ST13A'),
 (Timestamp('2023-01-13 00:00:00', freq='D'), 'Biba', 'ST24A'),
 (Timestamp('2023-01-13 00:00:00', freq='D'), 'Biba', 'ST25B'),
 (Timestamp('2023-01-13 00:00:00', freq='D'), 'Ciba', 'ST40A'),
 (Timestamp('2023-01-13 00:00:00', freq='D'), 'Ciba', 'ST35B'),
 (Timestamp('2023-01-13 00:00:00', freq='D'), 'Ciba', 'ST13A'),
 (Timestamp('2023-01-13 00:00:00', freq='D'), 'Ciba', 'ST24A'),
 (Timestamp('2023-01-13 00:00:00', freq='D'), 'Ciba', 'ST25B'),
 (Timestamp('2023-01-13 00:00:00', freq='D'), 'Aiba', 'ST40A'),
 (Timestamp('2023-01-13 00:00:00', freq='D'), 'Aiba', 'ST35B'),
 (Timestamp('2023-01-13 00:00:00', freq='D'), 'Aiba', 'ST13A'),
 (Timestamp('2023-01-13 00:00:00', freq='D'), 'Aiba', 'ST24A'),
 (Timestamp('2023-01-13 00:00:00', freq='D'), 'Aiba', 'ST25B'),
 (Timestamp('2023-01-14 00:00:00', freq='D'), 'Biba', 'ST40A'),
 (Timestamp('2023-01-14 00:00:00', freq='D'), 'Biba', 'ST35B'),
 (Timestamp('2023-01-14 00:00:00', freq='D'), 'Biba', 'ST13A'),
 (Timestamp('2023-01-14 00:00:00', freq='D'), 'Biba', 'ST24A'),
 (Timestamp('2023-01-14 00:00:00', freq='D'), 'Biba', 'ST25B'),
 (Timestamp('2023-01-14 00:00:00', freq='D'), 'Ciba', 'ST40A'),
 (Timestamp('2023-01-14 00:00:00', freq='D'), 'Ciba', 'ST35B'),
 (Timestamp('2023-01-14 00:00:00', freq='D'), 'Ciba', 'ST13A'),
 (Timestamp('2023-01-14 00:00:00', freq='D'), 'Ciba', 'ST24A'),
 (Timestamp('2023-01-14 00:00:00', freq='D'), 'Ciba', 'ST25B'),
 (Timestamp('2023-01-14 00:00:00', freq='D'), 'Aiba', 'ST40A'),
 (Timestamp('2023-01-14 00:00:00', freq='D'), 'Aiba', 'ST35B'),
 (Timestamp('2023-01-14 00:00:00', freq='D'), 'Aiba', 'ST13A'),
 (Timestamp('2023-01-14 00:00:00', freq='D'), 'Aiba', 'ST24A'),
 (Timestamp('2023-01-14 00:00:00', freq='D'), 'Aiba', 'ST25B'),
 (Timestamp('2023-01-15 00:00:00', freq='D'), 'Biba', 'ST40A'),
 (Timestamp('2023-01-15 00:00:00', freq='D'), 'Biba', 'ST35B'),
 (Timestamp('2023-01-15 00:00:00', freq='D'), 'Biba', 'ST13A'),
 (Timestamp('2023-01-15 00:00:00', freq='D'), 'Biba', 'ST24A'),
 (Timestamp('2023-01-15 00:00:00', freq='D'), 'Biba', 'ST25B'),
 (Timestamp('2023-01-15 00:00:00', freq='D'), 'Ciba', 'ST40A'),
 (Timestamp('2023-01-15 00:00:00', freq='D'), 'Ciba', 'ST35B'),
 (Timestamp('2023-01-15 00:00:00', freq='D'), 'Ciba', 'ST13A'),
 (Timestamp('2023-01-15 00:00:00', freq='D'), 'Ciba', 'ST24A'),
 (Timestamp('2023-01-15 00:00:00', freq='D'), 'Ciba', 'ST25B'),
 (Timestamp('2023-01-15 00:00:00', freq='D'), 'Aiba', 'ST40A'),
 (Timestamp('2023-01-15 00:00:00', freq='D'), 'Aiba', 'ST35B'),
 (Timestamp('2023-01-15 00:00:00', freq='D'), 'Aiba', 'ST13A'),
 (Timestamp('2023-01-15 00:00:00', freq='D'), 'Aiba', 'ST24A'),
 (Timestamp('2023-01-15 00:00:00', freq='D'), 'Aiba', 'ST25B'),
 (Timestamp('2023-01-16 00:00:00', freq='D'), 'Biba', 'ST40A'),
 (Timestamp('2023-01-16 00:00:00', freq='D'), 'Biba', 'ST35B'),
 (Timestamp('2023-01-16 00:00:00', freq='D'), 'Biba', 'ST13A'),
 (Timestamp('2023-01-16 00:00:00', freq='D'), 'Biba', 'ST24A'),
 (Timestamp('2023-01-16 00:00:00', freq='D'), 'Biba', 'ST25B'),
 (Timestamp('2023-01-16 00:00:00', freq='D'), 'Ciba', 'ST40A'),
 (Timestamp('2023-01-16 00:00:00', freq='D'), 'Ciba', 'ST35B'),
 (Timestamp('2023-01-16 00:00:00', freq='D'), 'Ciba', 'ST13A'),
 (Timestamp('2023-01-16 00:00:00', freq='D'), 'Ciba', 'ST24A'),
 (Timestamp('2023-01-16 00:00:00', freq='D'), 'Ciba', 'ST25B'),
 (Timestamp('2023-01-16 00:00:00', freq='D'), 'Aiba', 'ST40A'),
 (Timestamp('2023-01-16 00:00:00', freq='D'), 'Aiba', 'ST35B'),
 (Timestamp('2023-01-16 00:00:00', freq='D'), 'Aiba', 'ST13A'),
 (Timestamp('2023-01-16 00:00:00', freq='D'), 'Aiba', 'ST24A'),
 (Timestamp('2023-01-16 00:00:00', freq='D'), 'Aiba', 'ST25B'),
 (Timestamp('2023-01-17 00:00:00', freq='D'), 'Biba', 'ST40A'),
 (Timestamp('2023-01-17 00:00:00', freq='D'), 'Biba', 'ST35B'),
 (Timestamp('2023-01-17 00:00:00', freq='D'), 'Biba', 'ST13A'),
 (Timestamp('2023-01-17 00:00:00', freq='D'), 'Biba', 'ST24A'),
 (Timestamp('2023-01-17 00:00:00', freq='D'), 'Biba', 'ST25B'),
 (Timestamp('2023-01-17 00:00:00', freq='D'), 'Ciba', 'ST40A'),
 (Timestamp('2023-01-17 00:00:00', freq='D'), 'Ciba', 'ST35B'),
 (Timestamp('2023-01-17 00:00:00', freq='D'), 'Ciba', 'ST13A'),
 (Timestamp('2023-01-17 00:00:00', freq='D'), 'Ciba', 'ST24A'),
 (Timestamp('2023-01-17 00:00:00', freq='D'), 'Ciba', 'ST25B'),
 (Timestamp('2023-01-17 00:00:00', freq='D'), 'Aiba', 'ST40A'),
 (Timestamp('2023-01-17 00:00:00', freq='D'), 'Aiba', 'ST35B'),
 (Timestamp('2023-01-17 00:00:00', freq='D'), 'Aiba', 'ST13A'),
 (Timestamp('2023-01-17 00:00:00', freq='D'), 'Aiba', 'ST24A'),
 (Timestamp('2023-01-17 00:00:00', freq='D'), 'Aiba', 'ST25B'),
 (Timestamp('2023-01-18 00:00:00', freq='D'), 'Biba', 'ST40A'),
 (Timestamp('2023-01-18 00:00:00', freq='D'), 'Biba', 'ST35B'),
 (Timestamp('2023-01-18 00:00:00', freq='D'), 'Biba', 'ST13A'),
 (Timestamp('2023-01-18 00:00:00', freq='D'), 'Biba', 'ST24A'),
 (Timestamp('2023-01-18 00:00:00', freq='D'), 'Biba', 'ST25B'),
 (Timestamp('2023-01-18 00:00:00', freq='D'), 'Ciba', 'ST40A'),
 (Timestamp('2023-01-18 00:00:00', freq='D'), 'Ciba', 'ST35B'),
 (Timestamp('2023-01-18 00:00:00', freq='D'), 'Ciba', 'ST13A'),
 (Timestamp('2023-01-18 00:00:00', freq='D'), 'Ciba', 'ST24A'),
 (Timestamp('2023-01-18 00:00:00', freq='D'), 'Ciba', 'ST25B'),
 (Timestamp('2023-01-18 00:00:00', freq='D'), 'Aiba', 'ST40A'),
 (Timestamp('2023-01-18 00:00:00', freq='D'), 'Aiba', 'ST35B'),
 (Timestamp('2023-01-18 00:00:00', freq='D'), 'Aiba', 'ST13A'),
 (Timestamp('2023-01-18 00:00:00', freq='D'), 'Aiba', 'ST24A'),
 (Timestamp('2023-01-18 00:00:00', freq='D'), 'Aiba', 'ST25B'),
 (Timestamp('2023-01-19 00:00:00', freq='D'), 'Biba', 'ST40A'),
 (Timestamp('2023-01-19 00:00:00', freq='D'), 'Biba', 'ST35B'),
 (Timestamp('2023-01-19 00:00:00', freq='D'), 'Biba', 'ST13A'),
 (Timestamp('2023-01-19 00:00:00', freq='D'), 'Biba', 'ST24A'),
 (Timestamp('2023-01-19 00:00:00', freq='D'), 'Biba', 'ST25B'),
 (Timestamp('2023-01-19 00:00:00', freq='D'), 'Ciba', 'ST40A'),
 (Timestamp('2023-01-19 00:00:00', freq='D'), 'Ciba', 'ST35B'),
 (Timestamp('2023-01-19 00:00:00', freq='D'), 'Ciba', 'ST13A'),
 (Timestamp('2023-01-19 00:00:00', freq='D'), 'Ciba', 'ST24A'),
 (Timestamp('2023-01-19 00:00:00', freq='D'), 'Ciba', 'ST25B'),
 (Timestamp('2023-01-19 00:00:00', freq='D'), 'Aiba', 'ST40A'),
 (Timestamp('2023-01-19 00:00:00', freq='D'), 'Aiba', 'ST35B'),
 (Timestamp('2023-01-19 00:00:00', freq='D'), 'Aiba', 'ST13A'),
 (Timestamp('2023-01-19 00:00:00', freq='D'), 'Aiba', 'ST24A'),
 (Timestamp('2023-01-19 00:00:00', freq='D'), 'Aiba', 'ST25B'),
 (Timestamp('2023-01-20 00:00:00', freq='D'), 'Biba', 'ST40A'),
 (Timestamp('2023-01-20 00:00:00', freq='D'), 'Biba', 'ST35B'),
 (Timestamp('2023-01-20 00:00:00', freq='D'), 'Biba', 'ST13A'),
 (Timestamp('2023-01-20 00:00:00', freq='D'), 'Biba', 'ST24A'),
 (Timestamp('2023-01-20 00:00:00', freq='D'), 'Biba', 'ST25B'),
 (Timestamp('2023-01-20 00:00:00', freq='D'), 'Ciba', 'ST40A'),
 (Timestamp('2023-01-20 00:00:00', freq='D'), 'Ciba', 'ST35B'),
 (Timestamp('2023-01-20 00:00:00', freq='D'), 'Ciba', 'ST13A'),
 (Timestamp('2023-01-20 00:00:00', freq='D'), 'Ciba', 'ST24A'),
 (Timestamp('2023-01-20 00:00:00', freq='D'), 'Ciba', 'ST25B'),
 (Timestamp('2023-01-20 00:00:00', freq='D'), 'Aiba', 'ST40A'),
 (Timestamp('2023-01-20 00:00:00', freq='D'), 'Aiba', 'ST35B'),
 (Timestamp('2023-01-20 00:00:00', freq='D'), 'Aiba', 'ST13A'),
 (Timestamp('2023-01-20 00:00:00', freq='D'), 'Aiba', 'ST24A'),
 (Timestamp('2023-01-20 00:00:00', freq='D'), 'Aiba', 'ST25B'),
 (Timestamp('2023-01-21 00:00:00', freq='D'), 'Biba', 'ST40A'),
 (Timestamp('2023-01-21 00:00:00', freq='D'), 'Biba', 'ST35B'),
 (Timestamp('2023-01-21 00:00:00', freq='D'), 'Biba', 'ST13A'),
 (Timestamp('2023-01-21 00:00:00', freq='D'), 'Biba', 'ST24A'),
 (Timestamp('2023-01-21 00:00:00', freq='D'), 'Biba', 'ST25B'),
 (Timestamp('2023-01-21 00:00:00', freq='D'), 'Ciba', 'ST40A'),
 (Timestamp('2023-01-21 00:00:00', freq='D'), 'Ciba', 'ST35B'),
 (Timestamp('2023-01-21 00:00:00', freq='D'), 'Ciba', 'ST13A'),
 (Timestamp('2023-01-21 00:00:00', freq='D'), 'Ciba', 'ST24A'),
 (Timestamp('2023-01-21 00:00:00', freq='D'), 'Ciba', 'ST25B'),
 (Timestamp('2023-01-21 00:00:00', freq='D'), 'Aiba', 'ST40A'),
 (Timestamp('2023-01-21 00:00:00', freq='D'), 'Aiba', 'ST35B'),

### Create a New dataframe with combinations

In [47]:
df_combinations = pd.DataFrame(combinations,columns=['Billing Date','Brand','Site Name'])
df_combinations

     Billing Date Brand Site Name
0      2023-01-01  Biba     ST40A
1      2023-01-01  Biba     ST35B
2      2023-01-01  Biba     ST13A
3      2023-01-01  Biba     ST24A
4      2023-01-01  Biba     ST25B
...           ...   ...       ...
1015   2023-03-09  Aiba     ST40A
1016   2023-03-09  Aiba     ST35B
1017   2023-03-09  Aiba     ST13A
1018   2023-03-09  Aiba     ST24A
1019   2023-03-09  Aiba     ST25B

[1020 rows x 3 columns]

### Keep only rows in df_combinations that don't have a match in df1

In [48]:
anti_join = df_combinations.merge(df1[['Billing Date','Brand','Site Name']],
                                 on=['Billing Date','Brand','Site Name'],
                                 how='left',
                                 indicator=True)
anti_join

     Billing Date Brand Site Name     _merge
0      2023-01-01  Biba     ST40A  left_only
1      2023-01-01  Biba     ST35B  left_only
2      2023-01-01  Biba     ST13A  left_only
3      2023-01-01  Biba     ST24A  left_only
4      2023-01-01  Biba     ST25B  left_only
...           ...   ...       ...        ...
1015   2023-03-09  Aiba     ST40A  left_only
1016   2023-03-09  Aiba     ST35B  left_only
1017   2023-03-09  Aiba     ST13A  left_only
1018   2023-03-09  Aiba     ST24A  left_only
1019   2023-03-09  Aiba     ST25B  left_only

[1020 rows x 4 columns]

### Taking out those combinations Which are in the left Dataframe and not common

In [52]:
df_combinations=anti_join[anti_join['_merge']=='left_only']
df_combinations

     Billing Date Brand Site Name     _merge
0      2023-01-01  Biba     ST40A  left_only
1      2023-01-01  Biba     ST35B  left_only
2      2023-01-01  Biba     ST13A  left_only
3      2023-01-01  Biba     ST24A  left_only
4      2023-01-01  Biba     ST25B  left_only
...           ...   ...       ...        ...
1015   2023-03-09  Aiba     ST40A  left_only
1016   2023-03-09  Aiba     ST35B  left_only
1017   2023-03-09  Aiba     ST13A  left_only
1018   2023-03-09  Aiba     ST24A  left_only
1019   2023-03-09  Aiba     ST25B  left_only

[1015 rows x 4 columns]

### Dropping the _merge columns

In [53]:
df_combinations = df_combinations.drop(columns=['_merge'])
df_combinations

     Billing Date Brand Site Name
0      2023-01-01  Biba     ST40A
1      2023-01-01  Biba     ST35B
2      2023-01-01  Biba     ST13A
3      2023-01-01  Biba     ST24A
4      2023-01-01  Biba     ST25B
...           ...   ...       ...
1015   2023-03-09  Aiba     ST40A
1016   2023-03-09  Aiba     ST35B
1017   2023-03-09  Aiba     ST13A
1018   2023-03-09  Aiba     ST24A
1019   2023-03-09  Aiba     ST25B

[1015 rows x 3 columns]

### Getting the columns other then the combination

In [56]:
additional_columns=df1.columns.difference(['Billing Date','Brand','Site Name'])
additional_columns

Index(['Article', 'Bin', 'Brand Tag', 'Broad Craft', 'C Technique',
       'Craft Code', 'Fabric', 'Fiber', 'Handloom Mark', 'MRP',
       'POS Billing Quantity', 'POS Cost', 'POS Gross Sales',
       'POS Net Sales WOT', 'POS RGM', 'POS Tax Amount', 'POS Total Discount',
       'Promotion Name', 'Region', 'Silk Mark', 'Site', 'Site Area',
       'Style Code', 'Type', 'Vendor', 'Wash Care Instructions'],
      dtype='object')

### Set the Sales and Other Column values to 0 for the combinations

In [58]:
df_combinations[additional_columns]=0
df_combinations

,Billing Date,Brand,Site Name,Article,Bin,Brand Tag,Broad Craft,C Technique,Craft Code,Fabric,...,POS Total Discount,Promotion Name,Region,Silk Mark,Site,Site Area,Style Code,Type,Vendor,Wash Care Instructions
0,2023-01-01,Biba,ST40A,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2023-01-01,Biba,ST35B,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,2023-01-01,Biba,ST13A,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,2023-01-01,Biba,ST24A,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,2023-01-01,Biba,ST25B,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1015,2023-03-09,Aiba,ST40A,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1016,2023-03-09,Aiba,ST35B,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1017,2023-03-09,Aiba,ST13A,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1018,2023-03-09,Aiba,ST24A,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1019,2023-03-09,Aiba,ST25B,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

### Append the combinatios dfs to the original df

In [61]:
df1 = pd.concat([df1,df_combinations],ignore_index=True)
df1

,Billing Date,Brand,Article,Site,Site Area,MRP,Promotion Name,Region,POS Billing Quantity,POS Cost,...,Wash Care Instructions,C Technique,Broad Craft,Handloom Mark,Silk Mark,Type,Style Code,Craft Code,Site Name,Bin
0,2023-03-09,Biba,6517116692,ST40,A,7282,P37,R4,1,3486.742249,...,Handwash Separately,C6,B1,no,no,Printed,6517116,C6,ST40A,7000-7999
1,2023-01-10,Ciba,9792126013,ST35,B,6891,P20,R2,1,3366.377476,...,Handwash Separately,C3,B1,no,no,Embroidered,9792126,C3,ST35B,6000-6999
2,2023-01-30,Aiba,2451609893,ST13,A,1373,P16,R1,1,621.996417,...,Handwash Separately,C8,B1,no,no,Tie-Dyed,2451609,C8,ST13A,1000-1999
3,2023-02-08,Ciba,6919239963,ST24,A,4452,P2,R4,1,2182.635892,...,Handwash Separately,C6,B2,no,no,Embroidered,6919239,C6,ST24A,4000-4999
4,2023-01-01,Ciba,1418488906,ST25,B,5220,P13,R1,1,2421.383859,...,Handwash Separately,C4,B2,no,no,Embroidered,1418488,C4,ST25B,5000-5999
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1015,2023-03-09,Aiba,0,0,0,0,0,0,0,0.000000,...,0,0,0,0,0,0,0,0,ST40A,0
1016,2023-03-09,Aiba,0,0,0,0,0,0,0,0.000000,...,0,0,0,0,0,0,0,0,ST35B,0
1017,2023-03-09,Aiba,0,0,0,0,0,0,0,0.000000,...,0,0,0,0,0,0,0,0,ST13A,0
1018,2023-03-09,Aiba,0,0,0,0,0,0,0,0.000000,...,0,0,0,0,0,0,0,0,ST24A,0
1019,2023-03-09,Aiba,0,0,0,0,0,0,0,0.000000,...,0,0,0,0,0,0,0,0,ST25B,0